// <auto-generated />
using System;
using Kakeibo.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kakeibo.Api.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260307123554_AddWalletRolesAndVisibility")]
    partial class AddWalletRolesAndVisibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentSpending")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_spending");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<LocalDate>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsSeedData")
                        .HasColumnType("boolean")
                        .HasColumnName("is_seed_data");

                    b.Property<decimal>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_budgets");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_budgets_category_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_budgets_wallet_id");

                    b.HasIndex("UserId", "CategoryId")
                        .HasDatabaseName("ix_budgets_user_id_category_id");

                    b.HasIndex("UserId", "StartDate", "EndDate")
                        .HasDatabaseName("ix_budgets_user_id_start_date_end_date");

                    b.ToTable("budgets", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("background_color");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsSeedData")
                        .HasColumnType("boolean")
                        .HasColumnName("is_seed_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("TextColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("text_color");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_categories_user_id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            BackgroundColor = "#EFF6FF",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "Home",
                            IsSeedData = false,
                            Name = "Housing",
                            TextColor = "#1D4ED8",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            BackgroundColor = "#F0FDF4",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "Car",
                            IsSeedData = false,
                            Name = "Transportation",
                            TextColor = "#15803D",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            BackgroundColor = "#FFF7ED",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "UtensilsCrossed",
                            IsSeedData = false,
                            Name = "Food & Dining",
                            TextColor = "#C2410C",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            BackgroundColor = "#FFF1F2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "Heart",
                            IsSeedData = false,
                            Name = "Health & Wellness",
                            TextColor = "#BE123C",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            BackgroundColor = "#FAF5FF",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "Tv",
                            IsSeedData = false,
                            Name = "Entertainment & Leisure",
                            TextColor = "#7E22CE",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            BackgroundColor = "#FDF2F8",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "ShoppingCart",
                            IsSeedData = false,
                            Name = "Shopping & Personal",
                            TextColor = "#9D174D",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            BackgroundColor = "#EEF2FF",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "BookOpen",
                            IsSeedData = false,
                            Name = "Education",
                            TextColor = "#3730A3",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            BackgroundColor = "#F0FDFA",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "Repeat",
                            IsSeedData = false,
                            Name = "Subscriptions & Bills",
                            TextColor = "#0F766E",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            BackgroundColor = "#ECFDF5",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "PiggyBank",
                            IsSeedData = false,
                            Name = "Savings & Investments",
                            TextColor = "#065F46",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000a"),
                            BackgroundColor = "#FEFCE8",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "CreditCard",
                            IsSeedData = false,
                            Name = "Debt & Loans",
                            TextColor = "#854D0E",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000b"),
                            BackgroundColor = "#FFF1F2",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "Gift",
                            IsSeedData = false,
                            Name = "Gifts & Donations",
                            TextColor = "#9F1239",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-00000000000c"),
                            BackgroundColor = "#F9FAFB",
                            CreatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L),
                            Icon = "MoreHorizontal",
                            IsSeedData = false,
                            Name = "Other",
                            TextColor = "#374151",
                            UpdatedAt = NodaTime.Instant.FromUnixTimeTicks(17672256000000000L)
                        });
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_user_id");

                    b.Property<Instant?>("RejectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rejected_at");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_user_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_friend_requests");

                    b.HasIndex("ReceiverUserId")
                        .HasDatabaseName("ix_friend_requests_receiver_user_id");

                    b.HasIndex("SenderUserId", "ReceiverUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_friend_requests_sender_user_id_receiver_user_id");

                    b.ToTable("friend_requests", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Friendship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_a_id");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_b_id");

                    b.HasKey("Id")
                        .HasName("pk_friendships");

                    b.HasIndex("UserBId")
                        .HasDatabaseName("ix_friendships_user_b_id");

                    b.HasIndex("UserAId", "UserBId")
                        .IsUnique()
                        .HasDatabaseName("ix_friendships_user_a_id_user_b_id");

                    b.ToTable("friendships", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentProgress")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_progress");

                    b.Property<LocalDate?>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsSeedData")
                        .HasColumnType("boolean")
                        .HasColumnName("is_seed_data");

                    b.Property<int>("LastMilestone")
                        .HasColumnType("integer")
                        .HasColumnName("last_milestone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("target_amount");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_goals_user_id");

                    b.HasIndex("WalletId", "UserId")
                        .HasDatabaseName("ix_goals_wallet_id_user_id");

                    b.ToTable("goals", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InviteeEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("invitee_email");

                    b.Property<Guid>("InviterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("inviter_user_id");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_code");

                    b.HasIndex("InviterUserId")
                        .HasDatabaseName("ix_invitations_inviter_user_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_invitations_wallet_id");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("metadata");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.NotificationPreferences", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("EmailBudgetAlerts")
                        .HasColumnType("boolean")
                        .HasColumnName("email_budget_alerts");

                    b.Property<bool>("EmailGoalMilestones")
                        .HasColumnType("boolean")
                        .HasColumnName("email_goal_milestones");

                    b.Property<bool>("EmailInvitations")
                        .HasColumnType("boolean")
                        .HasColumnName("email_invitations");

                    b.Property<bool>("EmailRecurringUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("email_recurring_updates");

                    b.Property<bool>("PushBudgetAlerts")
                        .HasColumnType("boolean")
                        .HasColumnName("push_budget_alerts");

                    b.Property<bool>("PushGoalMilestones")
                        .HasColumnType("boolean")
                        .HasColumnName("push_goal_milestones");

                    b.Property<bool>("PushInvitations")
                        .HasColumnType("boolean")
                        .HasColumnName("push_invitations");

                    b.Property<bool>("PushRecurringUpdates")
                        .HasColumnType("boolean")
                        .HasColumnName("push_recurring_updates");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_notification_preferences");

                    b.ToTable("notification_preferences", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Instant?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("auth");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.RecurringPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DestinationWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_wallet_id");

                    b.Property<LocalDate?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsSeedData")
                        .HasColumnType("boolean")
                        .HasColumnName("is_seed_data");

                    b.Property<Instant?>("LastGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_generated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<LocalDate>("NextOccurrence")
                        .HasColumnType("date")
                        .HasColumnName("next_occurrence");

                    b.Property<LocalDate>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_recurring_patterns");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recurring_patterns_category_id");

                    b.HasIndex("DestinationWalletId")
                        .HasDatabaseName("ix_recurring_patterns_destination_wallet_id");

                    b.HasIndex("NextOccurrence")
                        .HasDatabaseName("ix_recurring_patterns_next_occurrence");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recurring_patterns_user_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_recurring_patterns_wallet_id");

                    b.HasIndex("UserId", "NextOccurrence")
                        .HasDatabaseName("ix_recurring_patterns_user_id_next_occurrence");

                    b.ToTable("recurring_patterns", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Instant?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_settlements");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_settlements_from_user_id");

                    b.HasIndex("ToUserId")
                        .HasDatabaseName("ix_settlements_to_user_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_settlements_wallet_id");

                    b.HasIndex("WalletId", "FromUserId", "ToUserId")
                        .HasDatabaseName("ix_settlements_wallet_id_from_user_id_to_user_id");

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<LocalDate>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DestinationWalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_wallet_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_transactions_date");

                    b.HasIndex("DestinationWalletId")
                        .HasDatabaseName("ix_transactions_destination_wallet_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_transactions_user_id");

                    b.HasIndex("WalletId")
                        .HasDatabaseName("ix_transactions_wallet_id");

                    b.HasIndex("WalletId", "Date")
                        .HasDatabaseName("ix_transactions_wallet_id_date");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.TransactionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_name");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_transaction_attachments");

                    b.HasIndex("TransactionId")
                        .HasDatabaseName("ix_transaction_attachments_transaction_id");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_transaction_attachments_uploaded_by_user_id");

                    b.ToTable("transaction_attachments", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CurrencyDecimalSeparator")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue(".")
                        .HasColumnName("currency_decimal_separator");

                    b.Property<string>("CurrencyDisplay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasDefaultValue("symbol")
                        .HasColumnName("currency_display");

                    b.Property<string>("CurrencyGroupSeparator")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValue(",")
                        .HasColumnName("currency_group_separator");

                    b.Property<string>("CurrencySymbolPosition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasDefaultValue("before")
                        .HasColumnName("currency_symbol_position");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Instant?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("email_verification_token");

                    b.Property<Instant?>("EmailVerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verification_token_expires_at");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<int>("MonthStartDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("month_start_day");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.Property<Instant?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<int>("WeekStartDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("week_start_day");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_id")
                        .HasFilter("google_id IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BackgroundColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("background_color");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsSeedData")
                        .HasColumnType("boolean")
                        .HasColumnName("is_seed_data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("TextColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("text_color");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Private")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.WalletBalance", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("WalletId")
                        .HasName("pk_wallet_balances");

                    b.ToTable("wallet_balances", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.WalletMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Guest")
                        .HasColumnName("role");

                    b.Property<Instant>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id")
                        .HasName("pk_wallet_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_wallet_members_user_id");

                    b.HasIndex("WalletId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallet_members_wallet_id_user_id");

                    b.ToTable("wallet_members", (string)null);
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Budget", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_categories_category_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_budgets_users_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_budgets_wallets_wallet_id");

                    b.Navigation("Category");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Category", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.FriendRequest", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friend_requests_users_receiver_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friend_requests_users_sender_user_id");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Friendship", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "UserA")
                        .WithMany()
                        .HasForeignKey("UserAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_users_user_a_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "UserB")
                        .WithMany()
                        .HasForeignKey("UserBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_users_user_b_id");

                    b.Navigation("UserA");

                    b.Navigation("UserB");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Goal", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goals_users_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goals_wallets_wallet_id");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Invitation", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_users_inviter_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_wallets_wallet_id");

                    b.Navigation("Inviter");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.NotificationPreferences", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Kakeibo.Api.Domain.Entities.NotificationPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_preferences_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.RecurringPattern", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_patterns_categories_category_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "DestinationWallet")
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recurring_patterns_wallets_destination_wallet_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_patterns_users_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_patterns_wallets_wallet_id");

                    b.Navigation("Category");

                    b.Navigation("DestinationWallet");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_users_from_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_users_to_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_wallets_wallet_id");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "DestinationWallet")
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_wallets_destination_wallet_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_users_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_wallets_wallet_id");

                    b.Navigation("Category");

                    b.Navigation("DestinationWallet");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.TransactionAttachment", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_attachments_transactions_transaction_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_attachments_users_uploaded_by_user_id");

                    b.Navigation("Transaction");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.WalletBalance", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "Wallet")
                        .WithOne("WalletBalance")
                        .HasForeignKey("Kakeibo.Api.Domain.Entities.WalletBalance", "WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_balances_wallets_wallet_id");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.WalletMember", b =>
                {
                    b.HasOne("Kakeibo.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_members_users_user_id");

                    b.HasOne("Kakeibo.Api.Domain.Entities.Wallet", "Wallet")
                        .WithMany("WalletMembers")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_members_wallets_wallet_id");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Kakeibo.Api.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("WalletBalance");

                    b.Navigation("WalletMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
